{
  imports = [
    ../modules/stylix.nix
    ../modules/audio.nix
    ../modules/bluetooth.nix
    ../modules/console.nix
    ../modules/displaymanager.nix
    ../modules/distrobox.nix
    ../modules/environment-variables.nix
    ../modules/firewall.nix
    ../modules/fonts.nix
    ../modules/fwupd.nix
    ../modules/gc.nix
    ../modules/graphics.nix
    ../modules/hacking.nix
    ../modules/i18n.nix
    ../modules/kernel.nix
    ../modules/networking.nix
    ../modules/nh.nix
    ../modules/nix-ld.nix
    ../modules/nix-settings.nix
    ../modules/nix-tools.nix
    ../modules/nix-auth.nix
    ../modules/openssh.nix
    ../modules/powermanagement.nix
    ../modules/security.nix
    ../modules/systemtools.nix
    ../modules/system-monitoring.nix
    ../modules/time.nix
    ../modules/virtualisation.nix
    ../modules/xdg.nix
    ../modules/zram.nix
    ../modules/zsh.nix
    ../modules/desktop/hyprland
  ];
}
