{
  imports = [
    ../modules/audio.nix
    ../modules/bluetooth.nix
    ../modules/displaymanager.nix
    ../modules/distrobox.nix
    ../modules/documentation.nix
    ../modules/environment-variables.nix
    ../modules/firewall.nix
    ../modules/fonts.nix
    ../modules/fwupd.nix
    ../modules/gc.nix
    ../modules/i18n.nix
    ../modules/kernel.nix
    ../modules/macchanger.nix
    ../modules/networking.nix
    ../modules/nh.nix
    ../modules/nix-ld.nix
    ../modules/nix-settings.nix
    ../modules/nix-tools.nix
    ../modules/nvf.nix
    ../modules/openssh.nix
    ../modules/powermanagement.nix
    ../modules/scanner.nix
    ../modules/security.nix
    ../modules/systemtools.nix
    ../modules/time.nix
    ../modules/xdg.nix
    ../modules/zram.nix
    ../modules/zsh.nix
    ../modules/desktop/hyprland.nix
  ];
}
