keys:
  - &primary age13ft29e8m924luedgy0cw08d0re7dtdvvelyurk82haqxv5sjd3mql2ymke
  - &ssh age12c3tc4mzrvr53x8fh6ajf824jdslk8q2cn46cfc6ar7sfg5g59mq3ymkym
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *primary


# .sops.yaml

keys:
  - &desktop age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp
  - &homie age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp
  - &laptop age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp
  - &nasty age16utg7mmk73cn3glrwthtm0p7mf6g3vrd48h3ucpn6wnf28pgxvcsh4rjjp

creation_rules:
  - path_regex: \.yaml$
    key_groups:
      - age:
          - *desktop
          - *nasty
          - *homie
          - *laptop

