{
  imports = [
    ../modules/alacritty.nix
    ../modules/environment-variables.nix
    ../modules/fish.nix
    ../modules/flatpak.nix
    ../modules/nixpkgs.nix
    ../modules/ghostty.nix
    ../modules/graphic.nix
    ../modules/helix.nix
    ../modules/kitty.nix
    ../modules/latex.nix
    ../modules/libreoffice.nix
    ../modules/meld.nix
    ../modules/messenger.nix
    ../modules/mission-center.nix
    ../modules/multimedia.nix
    ../modules/obs-studio.nix
    ../modules/pgbench.nix
    ../modules/gtk.nix
    ../modules/sh.nix
    ../modules/starship.nix
    ../modules/tmux.nix
    ../modules/torrent.nix
    ../modules/udiskie.nix
    ../modules/vscodium.nix
    ../modules/wallpapers.nix
    ../modules/wezterm.nix
    ../modules/zellij.nix
    ../modules/zoxide.nix
    ../modules/cli
    ../modules/nvf.nix
    ../modules/browsers/firefox.nix
    ../modules/browsers/chromium.nix
    ../modules/browsers/brave.nix
    ../modules/browsers/librewolf.nix
    ../modules/hyprland/hyprland2/animations.nix
    ../modules/hyprland/hyprland2/decorations.nix
    ../modules/hyprland/hyprland2/general.nix
    ../modules/hyprland/hyprland2/env.nix
    ../modules/hyprland/hyprland2/exec.nix
    ../modules/hyprland/hyprland2/keybindings.nix
    ../modules/hyprland/hyprland2/monitors.nix
    ../modules/hyprland/hyprland2/plugins/hypr-dynamic-cursors.nix
    ../modules/hyprland/hyprland2/plugins/hyprexpo.nix
    ../modules/hyprland/hyprland2/plugins/split-monitor-workspaces.nix
    ../modules/hyprland/hyprland2/main-config.nix
    ../modules/hyprland/hypridle.nix
    ../modules/hyprland/hyprpaper.nix
    ../modules/hyprland/rofi.nix
    ../modules/hyprland/hypridle.nix
    ../modules/hyprland/swaync.nix
    ../modules/hyprland/waybar.nix
    ../modules/hyprland/wlogout.nix
  ];
}
