{
  imports = [
    ../modules/alacritty.nix
    ../modules/clock-rs.nix
    ../modules/noctalia.nix
    ../modules/dconf.nix
    ../modules/environment-variables.nix
    ../modules/nixpkgs.nix
    ../modules/gtk.nix
    ../modules/graphic.nix
    ../modules/mime.nix
    ../modules/multimedia.nix
    ../modules/gtk.nix
    ../modules/sh.nix
    ../modules/starship.nix
    ../modules/stylix.nix
    ../modules/tmux.nix
    ../modules/udiskie.nix
    ../modules/vscodium.nix
    ../modules/wallpapers.nix
    ../modules/zoxide.nix
    ../modules/zsh.nix
    ../modules/cli
    ../modules/nvf
    #../modules/nixvim.nix
    ../modules/browsers
    ../modules/hyprland
  ];
}
