{
  imports = [
    ../modules/alacritty.nix
    ../modules/clock-rs.nix
    ../modules/noctalia.nix
    ../modules/dconf.nix
    ../modules/environment-variables.nix
    ../modules/nixpkgs.nix
    ../modules/gtk.nix
    ../modules/mime.nix
    ../modules/multimedia.nix
    ../modules/gtk.nix
    ../modules/sh.nix
    ../modules/starship.nix
    ../modules/stylix.nix
    ../modules/tmux.nix
    ../modules/udiskie.nix
    ../modules/vscodium.nix
    ../modules/wallpapers.nix
    ../modules/zsh.nix
    ../modules/cli/atiun.nix
    ../modules/cli/bash.nix
    ../modules/cli/bat.nix
    ../modules/cli/btop.nix
    ../modules/cli/dircolors.nix
    ../modules/cli/direnv.nix
    ../modules/cli/fastfetch.nix
    ../modules/cli/git.nix
    ../modules/cli/fzf.nix
    ../modules/nvf
    #../modules/nixvim.nix
    ../modules/browsers/firefox.nix
    ../modules/hyprland
  ];
}
